import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const spaceGrotesk = localFont({
  variable: "--font-space-grotesk",
  display: "swap",
  src: [
    {
      path: "../public/fonts/space-grotesk-400.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/space-grotesk-500.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/space-grotesk-700.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

const spaceMono = localFont({
  variable: "--font-space-mono",
  display: "swap",
  src: [
    {
      path: "../public/fonts/space-mono-400.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/space-mono-700.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${spaceMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
